# -*- coding: utf-8 -*-
"""emd_numerical_optimization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ki98BpyRQvpYJauvgxvt9yrvu4X8wD0x
"""

!pip install numpy scipy

import numpy as np
from scipy.optimize import linprog

# vectors
x = np.array([1, 3])
y = np.array([1, 2, 3])

# distributions
mu = np.array([1/2, 1/2])
nu = np.array([1/3, 1/3, 1/3])

# distance matrix
D = np.abs(x[:, None] - y[None, :])

# matrix to vector
c = D.flatten()

A_eq = []
b_eq = []

# rows=mu
for i in range(2):
    row = np.zeros(6)
    row[i*3:(i+1)*3] = 1
    A_eq.append(row)
    b_eq.append(mu[i])

# columns=nu
for j in range(3):
    col = np.zeros(6)
    col[j] = 1
    col[j+3] = 1
    A_eq.append(col)
    b_eq.append(nu[j])

A_eq = np.array(A_eq)
b_eq = np.array(b_eq)

# f_ij>=0
bounds = [(0, None)] * 6

res = linprog(c, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method="highs")

F = res.x.reshape(2, 3)

print("D =")
print(D)

print("\nF =")
print(F)

print("\nEMD =", res.fun)